(function(){
function $(s){return document.querySelector(s)} function $$(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function h5(){return typeof window.h5gg==='object'} function call(n){var a=Array.prototype.slice.call(arguments,1);if(h5()&&typeof h5gg[n]==='function')return h5gg[n].apply(h5gg,a);return null}
function esc(s){return String(s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
function na(v){v=String(v||'').trim();if(!v)return NaN;return /^0x/i.test(v)?parseInt(v,16):Number(v)} function ah(n){return '0x'+Math.floor(n).toString(16).toUpperCase()} function wh(n){return '0x'+((n>>>0).toString(16).toUpperCase().padStart(8,'0'))}
function bn(p){var a=String(p||'').split('/').filter(Boolean);return a.length?a[a.length-1]:'module'}
var S={results:[],snapshot:{},modules:[],armRows:[],bookmarks:[],history:[],watch:[],patches:[]};
['bookmarks','history','watch','patches'].forEach(function(k){try{S[k]=JSON.parse(localStorage.getItem('h5ggx.'+k)||'[]')}catch(e){}})
function save(){['bookmarks','history','watch','patches'].forEach(function(k){try{localStorage.setItem('h5ggx.'+k,JSON.stringify(S[k]))}catch(e){}})}
$('#mode').textContent=h5()?'H5GG LIVE':'DEMO';
function demo(){var a=[];for(var i=0;i<12;i++)a.push({address:ah(0x100000000+i*64),value:String((i+1)*10),type:$('#type').value});return a}
function loadResults(){var r=[];try{if(h5()){var c=Number(call('getResultsCount')||0);r=call('getResults',Math.min(c||100,500),0)||[]}else r=demo()}catch(e){}S.results=r.map(function(x){return {address:x.address||x.addr||'',value:String(x.value==null?'':x.value),type:x.type||$('#type').value,selected:false}});renderResults()}
function search(){var v=$('#value').value.trim(),t=$('#type').value,s=$('#rangeStart').value.trim(),e=$('#rangeEnd').value.trim();if(!v)return alert('検索値を入力してください');try{call('clearResults');call('searchNumber',v,t,s,e);S.history.unshift({value:v,type:t,start:s,end:e,ts:Date.now()});S.history=S.history.slice(0,50);save();renderHistory();loadResults()}catch(err){alert('検索エラー: '+err.message)}}
function nearby(){var v=$('#value').value.trim();if(!v)return alert('検索値を入力してください');try{call('searchNearby',v,$('#type').value,'0x100');loadResults()}catch(e){alert('Nearbyエラー')}}
function diff(x,m){if(m==='all')return true;var o=S.snapshot[x.address];if(typeof o==='undefined')return false;if(m==='changed')return String(o)!==String(x.value);if(m==='unchanged')return String(o)===String(x.value);var a=Number(o),b=Number(x.value);if(m==='increased')return isFinite(a)&&isFinite(b)&&b>a;if(m==='decreased')return isFinite(a)&&isFinite(b)&&b<a;return true}
function renderResults(){var q=$('#filter').value.toLowerCase(),m=$('#diffMode').value,a=S.results.filter(function(x){return (x.address+' '+x.value).toLowerCase().indexOf(q)>=0&&diff(x,m)});$('#resultList').innerHTML=a.length?a.map(function(x){return '<div class="item"><input type="checkbox" data-select="'+esc(x.address)+'"><div class="meta"><div class="val">'+esc(x.value)+'</div><div class="addr">'+esc(x.address)+'</div><div class="sub">'+esc(x.type)+'</div></div><div class="itemActions"><button class="mini" data-watch="'+esc(x.address)+'">監視</button><button class="mini" data-bookmark="'+esc(x.address)+'">保存</button></div></div>'}).join(''):'<div class="empty">結果なし</div>'}
function readVal(a,t){try{return h5()?String(call('getValue',a,t)):(S.results.find(function(x){return x.address===a})||{}).value||'?'}catch(e){return '?'}}
function renderWatch(){$('#watchList').innerHTML=S.watch.length?S.watch.map(function(x){return '<div class="item"><span>●</span><div class="meta"><div class="val">'+esc(readVal(x.address,x.type))+'</div><div class="addr">'+esc(x.address)+'</div><div class="sub">'+esc(x.type)+'</div></div><div class="itemActions"><button class="mini" data-delwatch="'+esc(x.address)+'">解除</button></div></div>'}).join(''):'<div class="empty">監視なし</div>'}
function renderBookmarks(){$('#bookmarkList').innerHTML=S.bookmarks.length?S.bookmarks.map(function(x){return '<div class="item"><span>★</span><div class="meta"><div class="val">'+esc(x.value)+'</div><div class="addr">'+esc(x.address)+'</div><div class="sub">'+esc(x.type)+'</div></div><div class="itemActions"><button class="mini" data-writebm="'+esc(x.address)+'">編集</button><button class="mini" data-delbm="'+esc(x.address)+'">削除</button></div></div>'}).join(''):'<div class="empty">保存なし</div>'}
function renderHistory(){$('#historyList').innerHTML=S.history.length?S.history.map(function(x,i){return '<div class="item"><span>↻</span><div class="meta"><div class="val">'+esc(x.value)+'</div><div class="sub">'+esc(x.type)+' ・ '+new Date(x.ts).toLocaleString()+'</div></div><div class="itemActions"><button class="mini" data-history="'+i+'">再検索</button></div></div>'}).join(''):'<div class="empty">履歴なし</div>'}
function loadModules(){var a=[];try{a=h5()?(call('getRangesList')||[]):[]}catch(e){}if(!a.length&&!h5())a=[{name:'/Demo/AppDemo',start:'0x100000000',end:'0x100020000'}];S.modules=a.map(function(m,i){return {name:m.name||('module'+i),start:String(m.start),end:String(m.end)}});$('#moduleSelect').innerHTML=S.modules.map(function(m,i){return '<option value="'+i+'">'+esc(bn(m.name))+' · '+esc(m.start)+'</option>'}).join('');showModule()}
function mod(){return S.modules[Number($('#moduleSelect').value)||0]||null} function showModule(){var m=mod();$('#moduleInfo').textContent=m?(m.name+'\nBASE '+m.start+'\nEND  '+m.end):'モジュールなし'}
function resolve(s){s=String(s||'').trim();var mm=s.match(/^(.+?)\+\s*(0x[0-9a-fA-F]+|\d+)$/);if(mm){var m=S.modules.find(function(x){return bn(x.name)===mm[1].trim()||x.name===mm[1].trim()})||mod();return m?na(m.start)+na(mm[2]):NaN}return na(s)}
function read32(a){try{var v=Number(call('getValue',ah(a),'U32'));return isFinite(v)?v>>>0:0}catch(e){return 0}}
function dec(w,a){w=w>>>0;if(w===0xD503201F)return 'NOP';if(w===0xD65F03C0)return 'RET';if((w&0xFFFFFC1F)===0xD61F0000)return 'BR X'+((w>>>5)&31);if((w&0xFFFFFC1F)===0xD63F0000)return 'BLR X'+((w>>>5)&31);if((w&0xFC000000)===0x14000000||(w&0xFC000000)===0x94000000){var im=w&0x03FFFFFF;if(im&0x02000000)im-=0x04000000;return ((w&0xFC000000)===0x94000000?'BL ':'B ')+ah(a+im*4)}return '.word '+wh(w)}
function readArm(){var s=resolve($('#armAddress').value);if(!isFinite(s))return alert('Offset / Address を確認してください');var c=Math.max(1,Math.min(128,Number($('#armCount').value)||24));s=Math.floor(s/4)*4;S.armRows=[];for(var i=0;i<c;i++){var a=s+i*4,w=h5()?read32(a):[0xD503201F,0x94000002,0xD65F03C0][i%3];S.armRows.push({address:ah(a),word:w,hex:wh(w),asm:dec(w,a)})}renderArm()}
function renderArm(){$('#armList').innerHTML=S.armRows.length?S.armRows.map(function(r){var p=S.patches.some(function(x){return x.address===r.address});return '<div class="armRow '+(p?'changedRuntime':'')+'"><div class="armTop"><div class="armAddr">'+r.address+'</div><div class="armHex">'+r.hex+'</div></div><div class="armAsm">'+esc(r.asm)+'</div><div class="armPatch"><button data-nop="'+r.address+'">NOP</button><input data-patchinput="'+r.address+'" value="'+r.hex.replace('0x','')+'" maxlength="8"><button data-patch="'+r.address+'">適用</button>'+(p?'<button data-restore="'+r.address+'">戻す</button>':'')+'</div></div>'}).join(''):'<div class="empty">まだ読み込んでいません</div>'}
function patch(a,h){if(!/^[0-9A-Fa-f]{8}$/.test(h))return alert('ARM64命令は8桁HEXで入力してください');var r=S.armRows.find(function(x){return x.address===a}),w=parseInt(h,16)>>>0;if(!r)return;try{if(h5()&&call('setValue',a,String(w),'U32')===false)return alert('書き込み失敗');if(!S.patches.some(function(x){return x.address===a}))S.patches.push({address:a,original:r.word});r.word=w;r.hex=wh(w);r.asm=dec(w,na(a));save();renderArm()}catch(e){alert('書き込みエラー: '+e.message)}}
function restore(a){var p=S.patches.find(function(x){return x.address===a});if(!p)return;try{if(h5())call('setValue',a,String(p.original>>>0),'U32');S.patches=S.patches.filter(function(x){return x.address!==a});save();readArm()}catch(e){}}
function tab(n){$$('.tabs button').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-tab')===n)});$$('.panel').forEach(function(p){p.classList.toggle('active',p.id===n)});if(n==='arm64'&&!S.modules.length)loadModules();if(n==='watch')renderWatch();window.scrollTo(0,0)}
$('#helpBtn').onclick=function(){var h=$('#helpCard');h.style.display=h.style.display==='none'?'block':'none'};$('#searchBtn').onclick=search;$('#nearBtn').onclick=nearby;$('#clearBtn').onclick=function(){call('clearResults');S.results=[];renderResults()};$('#filter').oninput=renderResults;$('#diffMode').onchange=renderResults;$('#snapshotBtn').onclick=function(){S.snapshot={};S.results.forEach(function(x){S.snapshot[x.address]=x.value})};$('#refreshBtn').onclick=function(){S.results.forEach(function(x){x.value=readVal(x.address,x.type)});renderResults()};$('#bulkSetBtn').onclick=function(){var v=$('#bulkValue').value;if(v==='')return;S.results.filter(function(x){return x.selected}).forEach(function(x){call('setValue',x.address,v,x.type);x.value=v});renderResults()};
$('#reloadModulesBtn').onclick=loadModules;$('#moduleSelect').onchange=showModule;$('#armUseModuleBtn').onclick=function(){var m=mod();if(m)$('#armAddress').value=m.start};$('#armOffsetBtn').onclick=function(){var m=mod(),o=$('#armAddress').value.trim();if(!m)return;if(!o)o='0x0';if(o.indexOf('+')<0)$('#armAddress').value=bn(m.name)+'+'+o};$('#armReadBtn').onclick=readArm;$$('.tabs button').forEach(function(b){b.onclick=function(){tab(b.getAttribute('data-tab'))}});
document.addEventListener('change',function(e){var a=e.target.getAttribute('data-select');if(a){var x=S.results.find(function(r){return r.address===a});if(x)x.selected=e.target.checked}});
document.addEventListener('click',function(e){var t=e.target,a;if((a=t.getAttribute('data-bookmark'))){var x=S.results.find(function(r){return r.address===a});if(x&&!S.bookmarks.some(function(b){return b.address===a})){S.bookmarks.unshift({address:x.address,value:x.value,type:x.type});save();renderBookmarks()}}if((a=t.getAttribute('data-watch'))){var y=S.results.find(function(r){return r.address===a});if(y&&!S.watch.some(function(b){return b.address===a})){S.watch.unshift({address:y.address,type:y.type});save();renderWatch()}}if((a=t.getAttribute('data-delwatch'))){S.watch=S.watch.filter(function(x){return x.address!==a});save();renderWatch()}if((a=t.getAttribute('data-delbm'))){S.bookmarks=S.bookmarks.filter(function(x){return x.address!==a});save();renderBookmarks()}if((a=t.getAttribute('data-writebm'))){var z=S.bookmarks.find(function(x){return x.address===a});if(z){var v=prompt('新しい値',z.value);if(v!==null){call('setValue',z.address,v,z.type);z.value=v;save();renderBookmarks()}}}var hi=t.getAttribute('data-history');if(hi!==null){var q=S.history[Number(hi)];if(q){$('#value').value=q.value;$('#type').value=q.type;$('#rangeStart').value=q.start;$('#rangeEnd').value=q.end;tab('results')}}if((a=t.getAttribute('data-nop')))patch(a,'D503201F');if((a=t.getAttribute('data-patch'))){var inp=document.querySelector('[data-patchinput="'+a+'"]');if(inp)patch(a,inp.value.trim())}if((a=t.getAttribute('data-restore')))restore(a)});
renderResults();renderBookmarks();renderHistory();renderWatch();renderArm();setInterval(function(){if(S.watch.length)renderWatch()},1000);
})();